# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

CREATE EXTERNAL TABLE `compute_cost`(
  `name` string, 
  `start` string, 
  `end` string, 
  `minutes` double, 
  `cpucores` double, 
  `cpucorerequestaverage` double, 
  `cpucoreusageaverage` double, 
  `cpucorehours` double, 
  `cpucost` double, 
  `cpucostadjustment` bigint, 
  `cpuefficiency` double, 
  `gpucount` bigint, 
  `gpuhours` bigint, 
  `gpucost` bigint, 
  `gpucostadjustment` bigint, 
  `networktransferbytes` double, 
  `networkreceivebytes` double, 
  `networkcost` bigint, 
  `networkcrosszonecost` bigint, 
  `networkcrossregioncost` bigint, 
  `networkinternetcost` bigint, 
  `networkcostadjustment` bigint, 
  `loadbalancercost` bigint, 
  `loadbalancercostadjustment` bigint, 
  `pvbytes` bigint, 
  `pvbytehours` bigint, 
  `pvcost` bigint, 
  `pvs` string, 
  `pvcostadjustment` bigint, 
  `rambytes` bigint, 
  `rambyterequestaverage` bigint, 
  `rambyteusageaverage` double, 
  `rambytehours` double, 
  `ramcost` string, 
  `ramcostadjustment` bigint, 
  `ramefficiency` double, 
  `externalcost` bigint, 
  `sharedcost` bigint, 
  `totalcost` double, 
  `totalefficiency` double, 
  `properties.cluster` string, 
  `properties.node` string, 
  `properties.container` string, 
  `properties.namespace` string, 
  `properties.pod` string, 
  `properties.providerid` string, 
  `properties.labels.emr_containers_amazonaws_com_component` string, 
  `properties.labels.emr_containers_amazonaws_com_job_id` string, 
  `properties.labels.emr_containers_amazonaws_com_resource_type` string, 
  `properties.labels.emr_containers_amazonaws_com_virtual_cluster_id` string, 
  `properties.labels.kubernetes_io_metadata_name` string, 
  `properties.labels.node_kubernetes_io_instance_type` string, 
  `properties.labels.spark_app_name` string, 
  `properties.labels.spark_app_selector` string, 
  `properties.labels.spark_driver_pod_name` string, 
  `properties.labels.spark_exec_id` bigint, 
  `properties.labels.spark_exec_resourceprofile_id` bigint, 
  `properties.labels.spark_role` string, 
  `properties.labels.spark_version` string, 
  `properties.labels.team` string, 
  `properties.labels.topology_kubernetes_io_region` string, 
  `properties.labels.topology_kubernetes_io_zone` string, 
  `window.start` string, 
  `window.end` string, 
  `rawallocationonly.cpucoreusagemax` double, 
  `rawallocationonly.rambyteusagemax` double, 
  `rawallocationonly` string, 
  `properties.controller` string, 
  `properties.controllerkind` string)
ROW FORMAT DELIMITED 
  FIELDS TERMINATED BY ',' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  's3://cost-data-REGION-ACCOUNT_ID/compute_cost/'
TBLPROPERTIES ( 
  'areColumnsQuoted'='false', 
  'classification'='csv', 
  'columnsOrdered'='true', 
  'compressionType'='none', 
  'delimiter'=',',
  'skip.header.line.count'='1')